language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libxml2-dev swig
install:
  - pip install pytest networkx
  - pip install -e .
# command to run tests
script:
  - python -m pytest
